# (provider, slug) pairs for public ATS job boards. Every slug here answered with live
# postings on 2026-09-29. Weighted toward global companies with India offices or
# India-eligible remote roles, since those pay well above the local market.
WATCHLIST = [
    ("greenhouse", "gitlab"),
    ("greenhouse", "okta"),
    ("greenhouse", "mongodb"),
    ("greenhouse", "elastic"),
    ("greenhouse", "cloudflare"),
    ("greenhouse", "databricks"),
    ("greenhouse", "twilio"),
    ("greenhouse", "samsara"),
    ("greenhouse", "coinbase"),
    ("greenhouse", "toast"),
    ("greenhouse", "hackerrank"),
    ("greenhouse", "druva"),
    ("greenhouse", "groww"),
    ("lever", "paytm"),
    ("lever", "meesho"),
    ("lever", "zeta"),
    ("lever", "cred"),
    ("ashby", "openai"),
    ("ashby", "perplexity"),
    ("ashby", "notion"),
    ("ashby", "linear"),
    ("ashby", "sarvam"),
    ("greenhouse", "stripe"),
    ("greenhouse", "anthropic"),
    ("greenhouse", "datadog"),
    ("greenhouse", "airbnb"),
    ("greenhouse", "pinterest"),
    ("greenhouse", "reddit"),
    ("greenhouse", "robinhood"),
    ("greenhouse", "lyft"),
    ("greenhouse", "dropbox"),
    ("greenhouse", "figma"),
    ("greenhouse", "instacart"),
    ("greenhouse", "affirm"),
    ("greenhouse", "asana"),
    ("greenhouse", "intercom"),
    ("greenhouse", "zscaler"),
    ("greenhouse", "purestorage"),
    ("greenhouse", "rubrik"),
    ("greenhouse", "block"),
    ("greenhouse", "roblox"),
    ("greenhouse", "epicgames"),
    ("greenhouse", "zoominfo"),
    ("greenhouse", "appian"),
    ("lever", "palantir"),
    ("lever", "spotify"),
    ("lever", "binance"),
    ("ashby", "snowflake"),
    ("ashby", "cohere"),
    ("ashby", "plaid"),
    ("ashby", "ramp"),
]
